{% set name = "nng" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nanomsg/nng/archive/v{{ version }}.tar.gz
  sha256: f639e77911ef935a13e9779d4a18d45490433ba744f89752a15b84c929ce2725
  patches:
    - test.patch  # [linux]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - ninja
  host:
    - mbedtls
  run:
    - ucrt  # [win]

test:
  commands:
    - test -f $PREFIX/lib/libnng.a  # [unix]

about:
  home: https://nng.nanomsg.org/
  summary: 'nanomsg-next-generation -- light-weight brokerless messaging'
  description: |
    nanomsg-next-generation -- light-weight brokerless messaging
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://nng.nanomsg.org/man/
  dev_url: https://github.com/nanomsg/nng

extra:
  recipe-maintainers:
    - jan-janssen
    - carlodri
