{% set name = "nng" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nanomsg/nng/archive/v{{ version }}.tar.gz
  sha256: e0af76aff291c670d091a07a4e71febf7b7a254f1ab5939f9464ccbd8f8aa2ba

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - ninja
  host:
  run:
    - ucrt  # [win]

test:
  commands:
    - test -f $PREFIX/lib/libnng.a  # [unix]

about:
  home: https://nng.nanomsg.org/
  summary: 'nanomsg-next-generation -- light-weight brokerless messaging'
  description: |
    nanomsg-next-generation -- light-weight brokerless messaging
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://nng.nanomsg.org/man/
  dev_url: https://github.com/nanomsg/nng

extra:
  recipe-maintainers:
    - jan-janssen
    - carlodri
